name: is_odd_new
description: Minimalist and elegant API that returns `true` if the given number or string is odd.
version: 0.0.3
homepage: https://github.com/ngoctienUIT/is_odd_new
repository: https://github.com/ngoctienUIT/is_odd_new

environment:
  sdk: '>=2.19.6 <3.0.0'

dev_dependencies:
  test: ^1.24.3

